kind: pipeline
type: docker
name: default

steps:
- name: build
  image: ubuntu
  commands:
  - apt update 
  - apt install default-jdk -y
  - apt install maven -y
  - mvn test
  - mvn package

- name: publish
  image: plugins/docker
  settings:
    username: sowjanya135
    password: D0cker@135
    repo: sowjanya135/drone-mvn
    tags:
    - 1.0
    
- name: deploy
  #pull: if-not-exists
  image: plugins/docker
  commands:
  #- apt-get update
  #- apt install sudo -y
  #- sudo su
  #- dockerd
  - docker run -itd -p 8086:8086 --name drone-test sowjanya135/drone-mvn:1
  #- service start docker
  #- docker-compose up 
